// Utility per ottenere un array di immagini delle carte
export const carteImages = [
  "2-bastoni.png",
  "2-coppe.png",
  "2-denara.png",
  "2-spade.png",
  "3-bastoni.png",
  "3-coppe.png",
  "3-denara.png",
  "3-spade.png",
  "4-bastoni.png",
  "4-coppe.png",
  "4-denara.png",
  "4-spade.png",
  "5-bastoni.png",
  "5-coppe.png",
  "5-denara.png",
  "5-spade.png",
  "6-bastoni.png",
  "6-coppe.png",
  "6-denara.png",
  "6-spade.png",
  "7-bastoni.png",
  "7-coppe.png",
  "7-denara.png",
  "7-spade.png",
  "A- Bastoni.png",
  "a-coppe.png",
  "a-denara.png",
  "a-spade.png",
  "C-bastoni.png",
  "c-coppe.png",
  "c-denara.png",
  "c-spade.png",
  "f-bastoni.png",
  "f-coppe.png",
  "f-denara.png",
  "f-spade.png",
  "r-bastoni.png",
  "r-coppe.png",
  "r-denara.png",
  "r-spade.png",
].map((name) => `/img/carte/${name}`);
